const env = {
	NEXT_PUBLIC_EXCHANGE_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_EXCHANGE_CONTRACT_ADDRESS,
	NEXT_PUBLIC_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_TOKEN_ADDRESS,
	NEXT_PUBLIC_NFT_ADDRESS: process.env.NEXT_PUBLIC_NFT_ADDRESS,
	NEXT_PUBLIC_NFT_PRESALE_ADDRESS: process.env.NEXT_PUBLIC_NFT_PRESALE_ADDRESS,
};

export const EXCHANGE_CONTRACT_ADDRESS = env.NEXT_PUBLIC_EXCHANGE_CONTRACT_ADDRESS || "";
export const TOKEN_ADDRESS = env.NEXT_PUBLIC_TOKEN_ADDRESS || "";
export const NFT_ADDRESS = env.NEXT_PUBLIC_NFT_ADDRESS || "";
export const NFT_PRESALE_ADDRESS = env.NEXT_PUBLIC_NFT_PRESALE_ADDRESS || "";
